config/routes.rb
Rails.application.routes.draw do
  resources :personnels

  get "password_resets/new"
  get 'current_user' => "personnels#current_user"
  get "sessions/new"
  get "reports/index"
  get "transaction/index"

  get "log_out" => 'sessions#destroy', :as => "log_out"
  get "log_in" => 'sessions#new', :as => "log_in"
  get "sign_up" => 'personnels#new', :as => "sign_up"
  root :to => 'personnels#new'
  resources :sessions
  resources :password_resets

# -----------------------------------------
  post 'setup/customer_index'
  get 'setup/customer_index'
  get 'setup/customer_new'
  post 'setup/customer_create'
  get 'setup/customer_edit'
  patch 'setup/customer_update'
  get 'setup/customer_destroy'

# -----------------------------------------
  get 'setup/index'
  post 'setup/lottery_index'
  get 'setup/lottery_index'
  get 'setup/lottery_new'
  post 'setup/lottery_create'
  get 'setup/lottery_edit'
  patch 'setup/lottery_update'
  get 'setup/lottery_destroy'

# -----------------------------------------
  post 'setup/series_index'
  get 'setup/series_index'
  get 'setup/series_new'
  post 'setup/series_create'
  get 'setup/series_edit'
  patch 'setup/series_update'
  get 'setup/series_destroy'
# -----------------------------------------

  get 'transaction/money_receipt_entry_form'
  post 'transaction/money_receipt_entry_form'
  get 'transaction/lottery_details_entry_form'
  post 'transaction/lottery_details_entry_form'
  get 'transaction/money_receipt_entry'
  post 'transaction/money_receipt_entry'
  get 'transaction/lottery_details_entry'
  post 'transaction/lottery_details_entry'
  get 'transaction/money_receipt_review'
  post 'transaction/money_receipt_review'
  get 'transaction/money_receipt_edit_form'
  post 'transaction/money_receipt_edit_form'
  get 'transaction/money_receipt_edit_entry'
  post 'transaction/money_receipt_edit_entry'
  get 'transaction/lottery_serial_input'
  post 'transaction/lottery_serial_input'
  get 'transaction/serial_input_appear'
  post 'transaction/serial_input_appear'
  get 'transaction/envelope_print'
  post 'transaction/envelope_print'
  post 'transaction/autocomplete_customer_name' => 'transaction#autocomplete_customer_name'
  get 'transaction/autocomplete_customer_name' => 'transaction#autocomplete_customer_name'
  post 'transaction/autocomplete_customer_mobile' => 'transaction#autocomplete_customer_mobile'
  get 'transaction/autocomplete_customer_mobile' => 'transaction#autocomplete_customer_mobile'
  get 'transaction/fetch_customer_details'
  post 'transaction/fetch_customer_details'
  get 'transaction/lottery_details_pending'
  post 'transaction/lottery_details_pending'
  get 'transaction/upload_instrument'
  post 'transaction/upload_instrument'
  get 'transaction/instrument_upload'
  post 'transaction/instrument_upload'
  get 'transaction/instruments_uploaded'
  post 'transaction/instruments_uploaded'
  get 'transaction/emo_entry'
  post 'transaction/emo_entry'
  get 'transaction/untagged_instruments'
  post 'transaction/untagged_instruments'
          

# -----------------------------------------
  post 'reports/money_receipt_register'
  get 'reports/money_receipt_register'


end

app/controllers/transaction_controller.rb
class TransactionController < ApplicationController
def index
end

def money_receipt_entry_form
end

def money_receipt_entry
Customer.transaction do	

# create customers
# create money receipt
old_customer_ids=[]
params[:customer][:id].each_with_index do |customer_id, index|
	if customer_id==nil || customer_id==''
		new_customer=Customer.new
		new_customer.name=params[:customer_name][index]
		new_customer.mobile=params[:customer_mobile][index]	
		new_customer.address=params[:customer][:address][index]
		new_customer.pincode=params[:customer][:pincode][index]
		new_customer.email=params[:customer][:email][index]
		new_customer.remarks=params[:customer][:remarks][index]
		new_customer.save

		money_receipt=MoneyReceipt.new
		money_receipt.customer_id=new_customer.id
			if params['instrument_type_'+((index+1).to_s)]=='MO'
			money_receipt.mo=true
			money_receipt.instrument_number=params[:customer][:instrument_number][index]
			elsif params['instrument_type_'+((index+1).to_s)]=='DD'
			money_receipt.dd=true
			money_receipt.instrument_number=params[:customer][:instrument_number][index]
			elsif params['instrument_type_'+((index+1).to_s)]=='Cash'
			money_receipt.cash=true
			elsif params['instrument_type_'+((index+1).to_s)]=='PWT'
			money_receipt.pwt=true	
			end
		money_receipt.amount=params[:customer][:amount][index]
		money_receipt.save

	else
		if old_customer_ids.include? customer_id
		new_customer=Customer.new
		new_customer.name=params[:customer_name][index]
		new_customer.mobile=params[:customer_mobile][index]	
		new_customer.address=params[:customer][:address][index]
		new_customer.pincode=params[:customer][:pincode][index]
		new_customer.email=params[:customer][:email][index]
		new_customer.remarks=params[:customer][:remarks][index]
		new_customer.save
		
		money_receipt=MoneyReceipt.new
		money_receipt.customer_id=new_customer.id
			if params['instrument_type_'+((index+1).to_s)]=='MO'
			money_receipt.mo=true
			money_receipt.instrument_number=params[:customer][:instrument_number][index]
			elsif params['instrument_type_'+((index+1).to_s)]=='DD'
			money_receipt.dd=true
			money_receipt.instrument_number=params[:customer][:instrument_number][index]
			elsif params['instrument_type_'+((index+1).to_s)]=='Cash'
			money_receipt.cash=true
			elsif params['instrument_type_'+((index+1).to_s)]=='PWT'
			money_receipt.pwt=true	
			end
		money_receipt.amount=params[:customer][:amount][index]
		money_receipt.save

		else
		old_customer_ids+=[customer_id]
		
		money_receipt=MoneyReceipt.new
		money_receipt.customer_id=customer_id.to_i
			if params['instrument_type_'+((index+1).to_s)]=='MO'
			money_receipt.mo=true
			money_receipt.instrument_number=params[:customer][:instrument_number][index]
			elsif params['instrument_type_'+((index+1).to_s)]=='DD'
			money_receipt.dd=true
			money_receipt.instrument_number=params[:customer][:instrument_number][index]
			elsif params['instrument_type_'+((index+1).to_s)]=='Cash'
			money_receipt.cash=true
			elsif params['instrument_type_'+((index+1).to_s)]=='PWT'
			money_receipt.pwt=true	
			end
		money_receipt.amount=params[:customer][:amount][index]
		money_receipt.save

		end
	end

end
redirect_to transaction_lottery_details_pending_url   
end
end

def lottery_details_pending
	@lottery_details_pending=MoneyReceipt.where(lottery_details_entered: nil)
end

def lottery_details_entry_form
	if params[:print]=="Print"
	redirect_to transaction_envelope_print_url :printables => params[:printables]
	else	
		@customers=[]
		lottery_details_pending=MoneyReceipt.where(lottery_details_entered: nil)
			lottery_details_pending.each do |lottery_details_pending|
				if lottery_details_pending.customer.mobile==nil
				@customers+=[[lottery_details_pending.customer.name+'-'+lottery_details_pending.amount.to_s+'-'+lottery_details_pending.instrument_detail, lottery_details_pending.id]]
				else
				@customers+=[[lottery_details_pending.customer.name+'-'+lottery_details_pending.amount.to_s+'-'+lottery_details_pending.customer.mobile+'-'+lottery_details_pending.instrument_detail, lottery_details_pending.id]]
				end
			end
		@customer=@customers.sort
		if params[:money_receipt_picked]==nil
		else
		@money_receipt_picked=params[:money_receipt_picked].to_i
		end

		@lotteries=[]
		  Lottery.where(drawn: nil).each do |lottery|
		  	@lotteries+=[[lottery.name, lottery.id]]
		  end
		  Lottery.where(drawn: false).each do |lottery|
		  	@lotteries+=[[lottery.name, lottery.id]]
		  end
		@lotteries=@lotteries.sort
	end
end

def lottery_serial_input
@inputs=params[:inputs]
@old_lottery_ids=params[:old_lottery_ids]
@old_lottery_ids=@old_lottery_ids.split(' ')
@inputs=@inputs.split(',')

@lotteries_remove=[]
@old_lottery_ids.each do |old_lottery_id|
  if @inputs.include?(old_lottery_id)
  else
  @lotteries_remove+=[old_lottery_id]
  end
end
@lotteries_add=[]

@inputs.each do |input|
  if @old_lottery_ids.include?(input)
  else
  @lotteries_add+=[input]
  end
end

  respond_to do |format|
      format.js { render :action => "lottery_input_serial"}
  end
end

def serial_input_appear
@series_id=params[:series_id]
@quantity=params[:quantity]
	respond_to do |format|
	      format.js { render :action => "serial_input_appear"}
	end
end

def autocomplete_customer_name
  customer_name = params[:term]
  customer_name=customer_name.gsub(/\(/, '')
  customer_name=customer_name.gsub(/\)/, '')
  customer_name=customer_name.gsub(/\&/, '')  
  customer_name=customer_name.gsub(/\s+$/, '')
  customer_name=customer_name.gsub(/\:/, '')
  customer_name=(customer_name.gsub(/\s+/, '&'))+":*"
  customers = Customer.where("to_tsvector(name) @@ to_tsquery(:q)", q: customer_name)
  render :json => customers.map { |customer| {:id => customer.id, :label => customer.name+"-"+customer.mobile , :value => customer.name } }
end

def autocomplete_customer_mobile
	customer_mobile = params[:term]
	customer_mobile=customer_mobile.gsub(/\(/, '')
	customer_mobile=customer_mobile.gsub(/\)/, '')
	customer_mobile=customer_mobile.gsub(/\&/, '')  
	customer_mobile=customer_mobile.gsub(/\s+$/, '')
	customer_mobile=customer_mobile.gsub(/\:/, '')
	customer_mobile=(customer_mobile.gsub(/\s+/, '&'))+":*"
	customers = Customer.where("to_tsvector(mobile) @@ to_tsquery(:q)", q: customer_mobile)
	render :json => customers.map { |customer| {:id => customer.id, :label => customer.mobile+"-"+customer.name , :value => customer.mobile } }
end

def fetch_customer_details
customer_id=params[:customer_id].to_i
@line_item_id=params[:id]

if @line_item_id.include? 'mobile'
@hidden_div_id=@line_item_id.sub 'customer_mobile', 'customer_div'
@customer_name_div_id=@line_item_id.sub 'customer_mobile', 'customer_name_div'
@customer_name_id=@line_item_id.sub 'customer_mobile', 'customer_name'
@customer_address_div_id=@line_item_id.sub 'customer_mobile', 'customer_address_div'
@customer_pincode_div_id=@line_item_id.sub 'customer_mobile', 'customer_pincode_div'
@customer_email_div_id=@line_item_id.sub 'customer_mobile', 'customer_email_div'
@customer_remarks_div_id=@line_item_id.sub 'customer_mobile', 'customer_remarks_div'
else
@hidden_div_id=@line_item_id.sub 'customer_name', 'customer_div'
@customer_mobile_div_id=@line_item_id.sub 'customer_name', 'customer_mobile_div'
@customer_mobile_id=@line_item_id.sub 'customer_name', 'customer_mobile'
@customer_address_div_id=@line_item_id.sub 'customer_name', 'customer_address_div'
@customer_pincode_div_id=@line_item_id.sub 'customer_name', 'customer_pincode_div'
@customer_email_div_id=@line_item_id.sub 'customer_name', 'customer_email_div'
@customer_remarks_div_id=@line_item_id.sub 'customer_name', 'customer_remarks_div'
end

@customer=Customer.find(customer_id)
	respond_to do |format|
		format.js { render :action => "set_customer_details"}
	end
end


def lottery_details_entry
  Lottery.transaction do	

	money_receipt=MoneyReceipt.find(params[:money_receipt][:id])
	money_receipt.update(rp_number: params[:rp_number], lottery_details_entered: true)
	
	params[:sold][:lotteries].each do |lottery_id|
		if lottery_id!=''
			sold_lottery=SoldLottery.new
			sold_lottery.money_receipt_id=money_receipt.id
			sold_lottery.lottery_id=lottery_id
			sold_lottery.save
			sold_lottery.lottery.series.each do |series|
				if params[series.id.to_s+'_serials']!=nil
					sold_series=SoldSeries.new
					sold_series.sold_lottery_id=sold_lottery.id
					sold_series.series_id=series.id
					sold_series.save
					params[series.id.to_s+'_serials'].each do |serial|
					sold_number=SoldNumber.new
					sold_number.sold_series_id=sold_series.id
					sold_number.serial=serial
					sold_number.save
					end
				end
			end
		end
	end	
  
  
  flash[:info]='Lottery Details Entry Done'
  redirect_to transaction_money_receipt_review_url :money_receipt_id => money_receipt.id 
  end
end

def money_receipt_review
@money_receipt=MoneyReceipt.find(params[:money_receipt_id])
	if params[:ok]=='OK'
	redirect_to transaction_lottery_details_pending_url
	elsif params[:edit]=='EDIT'
	redirect_to transaction_money_receipt_edit_form_url :money_receipt_id => @money_receipt.id
	end
end

def envelope_print
@printables=params[:printables]
@printables.each do |money_receipt_id|
money_receipt=MoneyReceipt.find(money_receipt_id)
money_receipt.update(printed: true)
end
render :layout => false
end

def money_receipt_edit_form
	@customers=[]
	lottery_details_pending=MoneyReceipt.where(lottery_details_entered: nil)
		lottery_details_pending.each do |lottery_details_pending|
		if lottery_details_pending.customer.mobile==nil
		@customers+=[[lottery_details_pending.customer.name+'-'+lottery_details_pending.amount.to_s+'-'+lottery_details_pending.instrument_detail, lottery_details_pending.id]]
		else
		@customers+=[[lottery_details_pending.customer.name+'-'+lottery_details_pending.amount.to_s+'-'+lottery_details_pending.customer.mobile+'-'+lottery_details_pending.instrument_detail, lottery_details_pending.id]]
		end
	end
	@money_receipt=MoneyReceipt.find(params[:money_receipt_id])	

app/helpers/transaction_helper.rb
module TransactionHelper
end

app/views/transaction/_customer_address.html.erb
<%= text_area_tag(("customer[address][]"), @customer.address, rows: "3", cols: "50", class: "form-control", required: true) %>

app/views/transaction/_customer_id.html.erb
<%= hidden_field_tag "customer[id][]", @customer.id %>

app/views/transaction/_customer_mobile.html.erb
<%= autocomplete_field_tag 'customer_mobile[]', @customer.mobile, transaction_autocomplete_customer_mobile_path, class: 'customer_mobile', id: @customer_mobile_id, size: 10 %>

app/views/transaction/_customer_name.html.erb
<%= autocomplete_field_tag 'customer_name[]', @customer.name, transaction_autocomplete_customer_name_path, class: 'customer_name', id: @customer_name_id, size: 25 %>

app/views/transaction/_customer_pincode.html.erb
<%= text_field_tag(("customer[pincode][]"), @customer.pincode, required: true, size: 7) %>

app/views/transaction/_serial_input_appear.html.erb
<br>
<% @quantity.to_i.times do %>
<%= text_field_tag(@series_id.to_s+"_serials[]", nil, style: "width:100px;", pattern: "[0-9]{5,}", title: "numeric between 5-7 characters", required: true, placeholder: 'Serial', class: "barcodeinput" ) %>
<% end %>
<br>
<br>

app/views/transaction/_updated_inputs.html.erb
<%= hidden_field_tag :old_lotteries, @inputs, id: 'old' %>

app/views/transaction/envelope_print.html.erb
<script>
$(document).ready(function() {
  $('.rotate').css('height', $('.rotate').width());
});
</script>
<style>
div {
   word-wrap: break-word;
   width: 300px;
   margin: 110px;
}
.rotate {
  /* FF3.5+ */
  -moz-transform: rotate(-90.0deg);
  /* Opera 10.5 */
  -o-transform: rotate(-90.0deg);
  /* Saf3.1+, Chrome */
  -webkit-transform: rotate(-90.0deg);
  /* IE6,IE7 */
  filter: progid: DXImageTransform.Microsoft.BasicImage(rotation=0.083);
  /* IE8 */
  -ms-filter: "progid:DXImageTransform.Microsoft.BasicImage(rotation=0.083)";
  /* Standard */
  transform: rotate(-90.0deg);
}
</style>

<% @printables.each do |money_receipt_id| %>
<% customer=MoneyReceipt.find(money_receipt_id).customer %>
<div class='rotate'>
<% if customer.mobile==nil || customer.mobile=="" %>
<% else %>
<p style="font-size:20px" align="right">
<i>Mobile:&nbsp<b><%= customer.mobile %></b></i><br>
</p>
<% end %>
<p style="font-size:20px;">
To,<br>  
<b><%= customer.name %></b><br>
<%= customer.address %><br>
PIN:&nbsp<%= customer.pincode %><br>
</p>
</div>

<p style="page-break-after: always;">&nbsp;</p>

<% end %>

app/views/transaction/index.html.erb
<div class="card border-primary mb-3" style="max-width: 30rem;">
<center>  
  <div class="card-header"></div>
  <div class="card-body">
      
    <h2 class="card-title">Transaction</h2>
      <ul class="list-group">

        <li class="list-group-item">
        <span class="badge"><%= %></span>
          <a>
          <span></span> 
          <%= link_to 'Customer Details', {controller: 'transaction', action: 'money_receipt_entry_form'}, {method: :post} %>
          </a>
        </li>

        <li class="list-group-item">
        <span class="badge"><%= %></span>
          <a>
          <span></span> 
          <%= link_to 'Pending Lottery Details', {controller: 'transaction', action: 'lottery_details_pending'}, {method: :post} %>
          </a>
        </li>

        <li class="list-group-item">
        <span class="badge"><%= %></span>
          <a>
          <span></span> 
          <%= link_to 'Customer Receipt Register', {controller: 'reports', action: 'money_receipt_register'}, {method: :post} %>
          </a>
        </li>        

        <li class="list-group-item">
        <span class="badge"><%= %></span>
          <a>
          <span></span> 
          <%= link_to 'Upload Instrument', {controller: 'transaction', action: 'upload_instrument'}, {method: :post} %>
          </a>
        </li>

        <li class="list-group-item">
        <span class="badge"><%= %></span>
          <a>
          <span></span> 
          <%= link_to 'Instruments Uploaded', {controller: 'transaction', action: 'instruments_uploaded'}, {method: :post} %>
          </a>
        </li>

        <li class="list-group-item">
        <span class="badge"><%= %></span>
          <a>
          <span></span> 
          <%= link_to 'Untagged Instruments', {controller: 'transaction', action: 'untagged_instruments'}, {method: :post} %>
          </a>
        </li>        

      </ul>
  </div>
</center>
</div>

app/views/transaction/instruments_uploaded.html.erb
<%= form_tag 'emo_entry', :authenticity_token => true, :html => {:class => 'form-horizontal'}  do %>

<div class="row row_position">
  <div class="col-sm-12">
    <div class='col-sm-3' id='total_amt'></div>
    <div class="col-sm-6">
      <h1>Instruments Uploaded</h1>
    </div>
     
  </div>      
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      
      <th><%= check_box_tag "selectAll", "selectAll" %></th>      
      <th>Date</th>
      <th>DocName</th>
      <th>Error</th>
      <th>Name</th>
      <th>Address</th>
      <th>Pin</th>
      <th>Mobile</th>
      <th>EMO</th>
      <th>Amount</th>
      
    </tr>
  </thead>

  <tbody>
    <%

    require "google/cloud/vision"

    Google::Cloud::Vision.configure do |config|
      config.project_id  = "lottery-220502"
      config.credentials = File.join(Rails.root, 'lottery-c12cc4ecd43a.json')
    end

    %>
    
    <% @instruments.each do |instrument| %>
    <tr>
      <td><%= check_box_tag 'instruments[]', instrument.id%></td>
      <td><%= instrument.created_at.strftime("%d/%m/%y") %></td>
      <td><%= link_to instrument.scan_file_name, instrument.scan.url, target: :_blank %></td>
      
      <%

      vision = Google::Cloud::Vision.new

      image = vision.image "https:"+instrument.scan.url

      @name=''
      @address=''
      @mobile=''
      @pincode=''
      @amount=''
      @emo_number=''

      document = image.document
      @text=document.text

      @error=''
      @name_and_address_index=@text.index('Name and Address')
      @payee_index=@text.index('Pay')
      if @name_and_address_index==nil || @payee_index==nil
        @error+=' name & address not detected'
      end
      @emo_number_index=@text.index('EMO NUMBER')
      @dated_index=@text.index('DATED')
      
      if @emo_number_index==nil || @dated_index==nil
        @error+=' emo number not detected'
      end
      
      @rs_index=@text.index('Rs.')
      @words_index=@text.index('words)')

      if @rs_index==nil || @words_index==nil
        @error+=' amount not detected'
      end

      if @error==''
      
      @name_and_address=@text[(@name_and_address_index+17)..(@payee_index-1)]
      @pincode=@name_and_address.scan(/\s[\d]{6}\s/).first.try{|x| x.strip}
      @mobile=@name_and_address.scan(/\s[\d]{10}\s/).first.try{|x| x.strip}

      if @pincode!=nil
      @name_and_address[@pincode]=""
      end

      if @mobile!=nil
      @name_and_address[@mobile]=""
      end

      @name=@name_and_address.scan(/\A\S+\s\S+/).first.try{|x| x.strip}
      if @name.length<=4
      @name=@name_and_address.scan(/\A\S+\s\S+\s\S+/).first.try{|x| x.strip}  
      end

      @name_and_address[@name]=""
      @address=@name_and_address
      

      @emo_number=@text[(@emo_number_index+12)..(@dated_index-2)]
      @amount=@text[(@rs_index+3)..(@words_index-6)]

      end

      %>
      <td><%= @error %></td>
      <td><%= @name %></td>
      <td><%= @address %></td>
      <td><%= @pincode %></td>
      <td><%= @mobile %></td>
      <td><%= @emo_number %></td>
      <td><%= @amount %></td>
      
    </tr>
    <% end %>
  </tbody>
</table>
<%= submit_tag "Enter eMO Details", name: "submit", :class => 'btn btn-primary btn-block' %>
<br>
<br>
<br>
<%= submit_tag "Remove", name: "submit", :class => 'btn btn-primary btn-block' %>
<% end %>

<script>

$(document).ready(function(){
$('#selectAll').click(function() {
   if (this.checked) {
       $(':checkbox').each(function() {
           this.checked = true;
       });
   } else {
      $(':checkbox').each(function() {
           this.checked = false;
       });
   }
});
});
  
</script>  

app/views/transaction/lottery_details_pending.html.erb
<%= form_tag 'lottery_details_entry_form', :authenticity_token => true, :html => {:class => 'form-horizontal'}  do %>
<div class="row row_position">
  <div class="col-sm-12">
    <div class='col-sm-3' id='total_amt'></div>
    <div class="col-sm-6">
      <h1>Pending Lottery Details</h1>
    </div>
     
  </div>      
</div>

<table class="table table-striped table-hover" id="lottery_details_pending">
  <thead>
    <tr>
      
      <th></th>
      <th>Date</th>
      <th>Edit</th>
      <th>Customer</th>
      <th>Address</th>
      <th>Pin</th>
      <th>Mobile</th>
      <th>Instrument</th>
      <th>Link</th>
      <th>Amount</th>
      <th>Print<%= check_box_tag "selectAll", "selectAll" %></th>
      <th>Printed</th>
    </tr>
  </thead>

  <tbody>
    <% @lottery_details_pending.each do |money_receipt| %>
    <tr>
      
      <td><%= radio_button_tag :money_receipt_picked, money_receipt.id, nil %></td>
      <td><%= money_receipt.created_at.strftime("%d/%m/%y") %></td>
      <td><%= link_to 'Edit', setup_customer_edit_path(money_receipt.customer) %></td>
      <td><%= money_receipt.customer.name %></td>
      <td><%= money_receipt.customer.address %></td>
      <td><%= money_receipt.customer.pincode %></td>
      <td><%= money_receipt.customer.mobile %></td>
      <td><%= money_receipt.instrument_detail %></td>
      <% if money_receipt.instrument==nil %>
      <td></td>
      <% else %>
      <td><%= link_to money_receipt.instrument.scan_file_name, money_receipt.instrument.scan.url, target: :_blank %></td>
      <% end %>
      <td><%= money_receipt.amount %></td>
      <td><%= check_box_tag 'printables[]', money_receipt.id%></td>
      <td><%= money_receipt.printed %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<div class="form-group">
 <div class="row">
  <div class="col-lg-6">
    <%= submit_tag "Enter Lottery Details", name: "submit", :class => 'btn btn-primary btn-block' %>
  </div>
  <div class="col-lg-6">
    <%= submit_tag "Print", name: "print", :class => 'btn btn-success btn-block' %>
  </div>
 </div> 
</div>

<% end %>

<script>
$(document).ready(function(){
$('#selectAll').click(function() {
   if (this.checked) {
       $(':checkbox').each(function() {
           this.checked = true;
       });
   } else {
      $(':checkbox').each(function() {
           this.checked = false;
       });
   }
});
});  
</script>  

app/views/transaction/serial_input_appear.js.erb
<% div_id='series_'+@series_id.to_s %>

$('#<%=div_id%>').empty()
$('#<%=div_id%>').append('<%= j render("serial_input_appear") %>')

$(document).ready(function() {
$(".multiple_lotteries").multiselect().multiselectfilter();
$(".ui-multiselect-all").hide();
$(".ui-multiselect-none").hide()
});

$(document).ready(function () {
    
    var keyupFiredCount = 0; 

    function DelayExecution(f, delay) {
        var timer = null; 
        return function () {
            var context = this, args = arguments;
           
            clearTimeout(timer);
            timer = window.setTimeout(function () {
                f.apply(context, args);
            },
            delay || 300);
        };
    }
    $.fn.ConvertToBarcodeTextbox = function () {

        $(this).focus(function () { $(this).select();$("#msg").html(""); });

         $(this).keydown(function (event) {
            var keycode = (event.keyCode ? event.keyCode : event.which); 
            
            if ($(this).val() == '') {
                keyupFiredCount = 0; 
            }  
            if (keycode == 13) {//enter key 
                    $(".nextcontrol").focus();
                    return false;
                    event.stopPropagation(); 
            } 
        });

        $(this).keyup(DelayExecution(function (event) {
            var keycode = (event.keyCode ? event.keyCode : event.which);  
                keyupFiredCount = keyupFiredCount + 1;  
        }));

         $(this).blur(function (event) { 
             if ($(this).val() == '')
                 return false;

             if(keyupFiredCount <= 1)
             {
                 $("#msg").html("<span style='color:green'>Its Scanner!</span>");
                 var final_text=''
                 var test_text=''
                 var test_number=0
                 final_text=$(this).val();
                 test_text=final_text.substr(final_text.length-5);

                 test_number=parseInt(test_text);
                 if (Number.isNaN(test_number))
                 {
                 final_text=final_text.substr(final_text.length-11,5);   
                 }
                 
                 final_text=final_text.substr(final_text.length-5);
                 

                 $(this).val(final_text);
                 //alert('Its Scanner'); 
             }
             else 
             {
                 $("#msg").html("<span style='color:red'>Its Manually Typed!</span>");
                 //alert('Its Manual Entry');
             }

             keyupFiredCount = 0;
         }); 
    };
    try {
        $(".barcodeinput").ConvertToBarcodeTextbox();
        if ($(".barcodeinput").val() == '')
            $(".barcodeinput").focus();
        else
            $(".nextcontrol").focus(); 
    } catch (e) { }

});