config/routes.rb
Rails.application.routes.draw do
  resources :personnels

  get "password_resets/new"
  get 'current_user' => "personnels#current_user"
  get "sessions/new"
  get "reports/index"
  get "transaction/index"

  get "log_out" => 'sessions#destroy', :as => "log_out"
  get "log_in" => 'sessions#new', :as => "log_in"
  get "sign_up" => 'personnels#new', :as => "sign_up"
  root :to => 'personnels#new'
  resources :sessions
  resources :password_resets

# -----------------------------------------
  post 'setup/customer_index'
  get 'setup/customer_index'
  get 'setup/customer_new'
  post 'setup/customer_create'
  get 'setup/customer_edit'
  patch 'setup/customer_update'
  get 'setup/customer_destroy'

# -----------------------------------------
  get 'setup/index'
  post 'setup/lottery_index'
  get 'setup/lottery_index'
  get 'setup/lottery_new'
  post 'setup/lottery_create'
  get 'setup/lottery_edit'
  patch 'setup/lottery_update'
  get 'setup/lottery_destroy'

# -----------------------------------------
  post 'setup/series_index'
  get 'setup/series_index'
  get 'setup/series_new'
  post 'setup/series_create'
  get 'setup/series_edit'
  patch 'setup/series_update'
  get 'setup/series_destroy'
# -----------------------------------------

  get 'transaction/money_receipt_entry_form'
  post 'transaction/money_receipt_entry_form'
  get 'transaction/lottery_details_entry_form'
  post 'transaction/lottery_details_entry_form'
  get 'transaction/money_receipt_entry'
  post 'transaction/money_receipt_entry'
  get 'transaction/lottery_details_entry'
  post 'transaction/lottery_details_entry'
  get 'transaction/money_receipt_review'
  post 'transaction/money_receipt_review'
  get 'transaction/money_receipt_edit_form'
  post 'transaction/money_receipt_edit_form'
  get 'transaction/money_receipt_edit_entry'
  post 'transaction/money_receipt_edit_entry'
  get 'transaction/lottery_serial_input'
  post 'transaction/lottery_serial_input'
  get 'transaction/serial_input_appear'
  post 'transaction/serial_input_appear'
  get 'transaction/envelope_print'
  post 'transaction/envelope_print'
  post 'transaction/autocomplete_customer_name' => 'transaction#autocomplete_customer_name'
  get 'transaction/autocomplete_customer_name' => 'transaction#autocomplete_customer_name'
  post 'transaction/autocomplete_customer_mobile' => 'transaction#autocomplete_customer_mobile'
  get 'transaction/autocomplete_customer_mobile' => 'transaction#autocomplete_customer_mobile'
  get 'transaction/fetch_customer_details'
  post 'transaction/fetch_customer_details'
  get 'transaction/lottery_details_pending'
  post 'transaction/lottery_details_pending'
  get 'transaction/upload_instrument'
  post 'transaction/upload_instrument'
  get 'transaction/instrument_upload'
  post 'transaction/instrument_upload'
  get 'transaction/instruments_uploaded'
  post 'transaction/instruments_uploaded'
  get 'transaction/emo_entry'
  post 'transaction/emo_entry'
  get 'transaction/untagged_instruments'
  post 'transaction/untagged_instruments'
          

# -----------------------------------------
  post 'reports/money_receipt_register'
  get 'reports/money_receipt_register'


end

app/controllers/setup_controller.rb
class SetupController < ApplicationController

def index
end

#--------------------------------------------------------------------
def customer_index
  @header='Lotteries'
  @search_in_navbar = true
  @customers=Customer.all 
end

def customer_new
  @header='Create Customer'
  @customer=Customer.new
  @customer_action='customer_create'
end

def customer_create
  @customer= Customer.new(customer_params)
  if params[:customer][:mobile]!=''
  	if Customer.find_by_mobile(params[:customer][:mobile])==nil
  	@customer.save	
  	flash[:info]='Customer was successfully created.'
  	else
  	flash[:danger]='Customer not created, as same mobile no. detected'
  	end
  else
  @customer.save
  flash[:info]='Customer was successfully created.'
  end
  redirect_to setup_customer_index_url
end

def customer_edit
  @header='Edit customer' 
  @customer=Customer.find(params[:format])
  @customer_action='customer_update' 
end

def customer_update
  @customer=Customer.find(params[:customer_id])
  @customer.update(customer_params)
  flash[:info]='Customer was successfully updated.'
  redirect_to transaction_lottery_details_pending_url
end

def customer_destroy
  @customer=Customer.find(params[:format])
  if MoneyReceipt.find_by_customer_id(@customer.id)==nil
  @customer.destroy
  flash[:info]='Customer was successfully destroyed.'
  else
  flash[:danger]='Customer could not be destroyed, money receipt exists against the same'  
  end
  redirect_to setup_customer_index_url
end

#--------------------------------------------------------------------

def lottery_index
  @header='Lotteries'
  @search_in_navbar = true
  @lotteries=Lottery.all 
end

def lottery_new
  @header='Create Lottery'
  @lottery=Lottery.new
  @lottery_action='lottery_create'
end

def lottery_create
  @lottery= Lottery.new(lottery_params)
  @lottery.save
  flash[:info]='Lottery was successfully created.'
  redirect_to setup_lottery_index_url
end

def lottery_edit
  @header='Edit Lottery' 
  @lottery=Lottery.find(params[:format])
  @lottery_action='lottery_update' 
end

def lottery_update
  @lottery=Lottery.find(params[:lottery_id])
  @lottery.update(lottery_params)
  flash[:info]='Lottery was successfully updated.'
  redirect_to setup_lottery_index_url
end

def lottery_destroy
  @lottery=Lottery.find(params[:format])
  if Series.find_by_lottery_id(@lottery.id)==nil
  @lottery.destroy
  flash[:info]='Lottery was successfully destroyed.'
  else
  flash[:danger]='Lottery could not be destroyed, Series exists against the same'  
  end
  redirect_to setup_lottery_index_url
end

#--------------------------------------------------------------------

def series_index
  @header='Lotteries'
  @search_in_navbar = true
  @series=Series.all 
end

def series_new
  @lotteries=[]
  Lottery.where(drawn: nil).each do |lottery|
  	@lotteries+=[[lottery.name, lottery.id]]
  end
  Lottery.where(drawn: false).each do |lottery|
  	@lotteries+=[[lottery.name, lottery.id]]
  end
  @lotteries=@lotteries.sort

  @header='Create Series'
  @series=Series.new
  @series_action='series_create'
end

def series_create
  @series= Series.new(series_params)
  @series.save
  flash[:info]='Series was successfully created.'
  redirect_to setup_series_index_url
end

def series_edit
  @lotteries=[]
  Lottery.where.not(drawn: true).each do |lottery|
  	@lotteries+=[[lottery.name, lottery.id]]
  end
  @lotteries=@lotteries.sort
  
  @header='Edit Series' 
  @series=Series.find(params[:format])
  @series_action='series_update' 
end

def series_update
  @series=Series.find(params[:series_id])
  @series.update(series_params)
  flash[:info]='Series was successfully updated.'
  redirect_to setup_series_index_url
end

def series_destroy
  @series=Series.find(params[:format])
  if Series.find_by_series_id(@series.id)==nil
  @series.destroy
  flash[:info]='Series was successfully destroyed.'
  else
  flash[:danger]='Series could not be destroyed, sale exists against the same'  
  end
  redirect_to setup_series_index_url
end

def lottery_params
  params.require(:lottery).permit(:name,:rate,:drawn)
end

def customer_params
  params.require(:customer).permit(:name,:address,:pincode,:mobile,:email,:remarks)
end

def series_params
  params.require(:series).permit(:name,:lottery_id)
end

end

app/helpers/setup_helper.rb
module SetupHelper
end

app/views/setup/_customer_form.html.erb
<%= form_for @customer,:html=> {:class=>"form-horizontal"}, url: {action: @customer_action} do |f| %>


  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-lg-5 col-lg-offset-4">
    <div class="well bs-component">
      <legend>New Customer Entry</legend>
      
        <div class="form-group">
           <%= f.label :name, :class => 'col-lg-2 control-label' %>
              <div class="col-lg-8">
                <%= f.text_field :name,:class => 'form-control', required: true  %>
              </div>
        </div>

        <div class="form-group">
           <%= f.label :address, :class => 'col-lg-2 control-label' %>
              <div class="col-lg-8">
                <%= f.text_area :address, :class => 'form-control', rows: "6", required: true  %>
              </div>
        </div>

        <div class="form-group">
           <%= f.label :pincode, :class => 'col-lg-2 control-label' %>
              <div class="col-lg-8">
                <%= f.text_field :pincode,:class => 'form-control', required: true  %>
              </div>
        </div>

        <div class="form-group">
           <%= f.label :mobile, :class => 'col-lg-2 control-label' %>
              <div class="col-lg-8">
                <%= f.text_field :mobile,:class => 'form-control'  %>
              </div>
        </div>

        <div class="form-group">
           <%= f.label :email, :class => 'col-lg-2 control-label' %>
              <div class="col-lg-8">
                <%= f.text_field :email, :class => 'form-control'  %>
              </div>
        </div>

        <div class="form-group">
           <%= f.label :remarks, :class => 'col-lg-2 control-label' %>
              <div class="col-lg-8">
                <%= f.text_field :remarks, :class => 'form-control'  %>
              </div>
        </div>


      <div class="form-group">
      <div class="col-lg-8 col-lg-offset-2">
         <%= f.submit :class => 'btn btn-primary btn-block' %>
      </div>
 </div>
<%= hidden_field_tag :customer_id, @customer.id %>
</div>
</div>
<% end %>

app/views/setup/_lottery_form.html.erb
<%= form_for @lottery,:html=> {:class=>"form-horizontal"}, url: {action: @lottery_action} do |f| %>


  <% if @lottery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lottery.errors.count, "error") %> prohibited this lottery from being saved:</h2>

      <ul>
      <% @lottery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-lg-5 col-lg-offset-4">
    <div class="well bs-component">
      <legend>New Lottery Entry</legend>
      
        <div class="form-group">
           <%= f.label :name, :class => 'col-lg-2 control-label' %>
              <div class="col-lg-8">
                <%= f.text_field :name,:class => 'form-control', required: true  %>
              </div>
        </div>

        <div class="form-group">
           <%= f.label :rate, :class => 'col-lg-2 control-label' %>
              <div class="col-lg-8">
                <%= f.number_field :rate,:class => 'form-control', required: true  %>
              </div>
        </div>

        <% if @lottery_action=='lottery_update' %>
        <div class="form-group">
           <%= f.label :drawn, :class => 'col-lg-2 control-label' %>
              <div class="col-lg-8">
                <%= f.check_box :drawn, {},"1","0" %>
              </div>
        </div>
        <% end %>
        

      <div class="form-group">
      <div class="col-lg-8 col-lg-offset-2">
         <%= f.submit :class => 'btn btn-primary btn-block' %>
      </div>
 </div>
<%= hidden_field_tag :lottery_id, @lottery.id %>
</div>
</div>
<% end %>

app/views/setup/_series_form.html.erb
<%= form_for @series,:html=> {:class=>"form-horizontal"}, url: {action: @series_action} do |f| %>


  <% if @series.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@series.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
      <% @series.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-lg-5 col-lg-offset-4">
    <div class="well bs-component">
      <legend>New Series Entry</legend>
      
        <div class="form-group">
           <%= f.label :lottery, :class => 'col-lg-2 control-label' %>
            <div class="col-lg-8">
              <%= select(:series, :lottery_id, options_for_select(@lotteries, selected: @series.lottery_id),{}, {class: "form-control" }) %>
            </div>
        </div>

        <div class="form-group">
           <%= f.label :name, :class => 'col-lg-2 control-label' %>
              <div class="col-lg-8">
                <%= f.text_field :name,:class => 'form-control', required: true  %>
              </div>
        </div>



      <div class="form-group">
      <div class="col-lg-8 col-lg-offset-2">
         <%= f.submit :class => 'btn btn-primary btn-block' %>
      </div>
 </div>
<%= hidden_field_tag :series_id, @series.id %>
</div>
</div>
<% end %>

app/views/setup/customer_edit.html.erb
<%= render 'customer_form' %>

app/views/setup/customer_index.html.erb
<h1>Customer List</h1>

<table class="table table-striped table-hover" id="customer_index">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Pincode</th>
      <th>Mobile</th>
      <th>Email</th>
      <th>Remarks</th>
      <th></th>
      <th></th>
    </tr> 
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.address %></td>
        <td><%= customer.pincode %></td>
        <td><%= customer.mobile %></td>
        <td><%= customer.email %></td>
        <td><%= customer.remarks %></td>
        <td><%= link_to 'Edit', setup_customer_edit_path(customer) %></td>
        <td><%= link_to 'Destroy', setup_customer_destroy_path(customer), data: {confirm: 'Are you sure?'} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New Customer', setup_customer_new_path, :class => 'btn btn-primary' %>

app/views/setup/customer_new.html.erb
<%= render 'customer_form' %>

app/views/setup/index.html.erb
<div class="card border-primary mb-3" style="max-width: 30rem;">
<center>  
  <div class="card-header"></div>
  <div class="card-body">
    <h2 class="card-title">Setup</h2>
      <ul class="list-group">

        <li class="list-group-item">
        <span class="badge"><%= %></span>
          <a>
          <span></span> 
          <%= link_to 'Customers', {controller: 'setup', action: 'customer_index'}, {method: :post} %>
          </a>
        </li>        

        <li class="list-group-item">
        <span class="badge"><%= %></span>
          <a>
          <span></span> 
          <%= link_to 'Lotteries', {controller: 'setup', action: 'lottery_index'}, {method: :post} %>
          </a>
        </li>

        <li class="list-group-item">
        <span class="badge"><%= %></span>
          <a>
          <span></span> 
          <%= link_to 'Series', {controller: 'setup', action: 'series_index'}, {method: :post} %>
          </a>
        </li>

      </ul>
  </div>
</div>
</center>

app/views/setup/lottery_edit.html.erb
<%= render 'lottery_form' %>

app/views/setup/lottery_index.html.erb
<h1>Lottery List</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Series</th>
      <th>Rate</th>
      <th>Drawn</th>
      <th></th>
      <th></th>
    </tr> 
  </thead>

  <tbody>
    <% @lotteries.each do |lottery| %>
      <tr>
        <td><%= lottery.name %></td>
        <td><%= lottery.series.pluck(:name).map(&:inspect).join(', ').gsub('"', '') %></td>
        <td><%= lottery.rate.round %></td>
        <td><%= lottery.drawn %></td>
        <td><%= link_to 'Edit', setup_lottery_edit_path(lottery) %></td>
        <td><%= link_to 'Destroy', setup_lottery_destroy_path(lottery),data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New Lottery ', setup_lottery_new_path, :class => 'btn btn-primary' %>

app/views/setup/lottery_new.html.erb
<%= render 'lottery_form' %>

app/views/setup/series_edit.html.erb
<%= render 'series_form' %>

app/views/setup/series_index.html.erb
<h1>Series List</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Lottery</th>
      <th>Series Name</th>
      <th></th>
      <th></th>
    </tr> 
  </thead>

  <tbody>
    <% @series.each do |serial| %>
      <tr>
        <td><%= serial.lottery.name %></td>
        <td><%= serial.name %></td>
        <td><%= link_to 'Edit', setup_series_edit_path(serial) %></td>
        <td><%= link_to 'Destroy', setup_series_destroy_path(serial),data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New Series', setup_series_new_path, :class => 'btn btn-primary' %>

app/views/setup/series_new.html.erb
<%= render 'series_form' %>