config/routes.rb
Rails.application.routes.draw do
  resources :personnels

  get "password_resets/new"
  get 'current_user' => "personnels#current_user"
  get "sessions/new"
  get "reports/index"
  get "transaction/index"

  get "log_out" => 'sessions#destroy', :as => "log_out"
  get "log_in" => 'sessions#new', :as => "log_in"
  get "sign_up" => 'personnels#new', :as => "sign_up"
  root :to => 'personnels#new'
  resources :sessions
  resources :password_resets

# -----------------------------------------
  post 'setup/customer_index'
  get 'setup/customer_index'
  get 'setup/customer_new'
  post 'setup/customer_create'
  get 'setup/customer_edit'
  patch 'setup/customer_update'
  get 'setup/customer_destroy'

# -----------------------------------------
  get 'setup/index'
  post 'setup/lottery_index'
  get 'setup/lottery_index'
  get 'setup/lottery_new'
  post 'setup/lottery_create'
  get 'setup/lottery_edit'
  patch 'setup/lottery_update'
  get 'setup/lottery_destroy'

# -----------------------------------------
  post 'setup/series_index'
  get 'setup/series_index'
  get 'setup/series_new'
  post 'setup/series_create'
  get 'setup/series_edit'
  patch 'setup/series_update'
  get 'setup/series_destroy'
# -----------------------------------------

  get 'transaction/money_receipt_entry_form'
  post 'transaction/money_receipt_entry_form'
  get 'transaction/lottery_details_entry_form'
  post 'transaction/lottery_details_entry_form'
  get 'transaction/money_receipt_entry'
  post 'transaction/money_receipt_entry'
  get 'transaction/lottery_details_entry'
  post 'transaction/lottery_details_entry'
  get 'transaction/money_receipt_review'
  post 'transaction/money_receipt_review'
  get 'transaction/money_receipt_edit_form'
  post 'transaction/money_receipt_edit_form'
  get 'transaction/money_receipt_edit_entry'
  post 'transaction/money_receipt_edit_entry'
  get 'transaction/lottery_serial_input'
  post 'transaction/lottery_serial_input'
  get 'transaction/serial_input_appear'
  post 'transaction/serial_input_appear'
  get 'transaction/envelope_print'
  post 'transaction/envelope_print'
  post 'transaction/autocomplete_customer_name' => 'transaction#autocomplete_customer_name'
  get 'transaction/autocomplete_customer_name' => 'transaction#autocomplete_customer_name'
  post 'transaction/autocomplete_customer_mobile' => 'transaction#autocomplete_customer_mobile'
  get 'transaction/autocomplete_customer_mobile' => 'transaction#autocomplete_customer_mobile'
  get 'transaction/fetch_customer_details'
  post 'transaction/fetch_customer_details'
  get 'transaction/lottery_details_pending'
  post 'transaction/lottery_details_pending'
  get 'transaction/upload_instrument'
  post 'transaction/upload_instrument'
  get 'transaction/instrument_upload'
  post 'transaction/instrument_upload'
  get 'transaction/instruments_uploaded'
  post 'transaction/instruments_uploaded'
  get 'transaction/emo_entry'
  post 'transaction/emo_entry'
  get 'transaction/untagged_instruments'
  post 'transaction/untagged_instruments'
          

# -----------------------------------------
  post 'reports/money_receipt_register'
  get 'reports/money_receipt_register'


end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

def index
end

def money_receipt_register
	if params[:print]=="Print"
		redirect_to transaction_envelope_print_url :printables => params[:printables] 
  	else
		@header = 'Register'
		@search_in_navbar = true
		@from=(Date.today)
		@to=(Date.today)+1
	  	
	  	if params[:range] != nil
	    @from=params[:range][:from]
	    @to=params[:range][:to]
	  	end
		@money_receipts=MoneyReceipt.includes(:sold_lotteries, :customer).where('money_receipts.created_at >=  ? AND money_receipts.created_at < ? AND money_receipts.lottery_details_entered = ?',@from, @to, true)
	end
end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/home.html.erb
<div class="col-lg-4 col-lg-offset-4">

<div class="card border-success mb-3" style="max-width: 20rem;">
  <div class="card-header">Jain Group</div>
  <div class="card-body">
    <h4 class="card-title">MIS</h4>
    <br>
    <%= button_to "Outstanding", "http://postcrm.herokuapp.com/window/outstanding_summary", :class => "btn btn-primary btn-lg btn-block", :method => :post %>
    <br>
    <%= button_to "Collection", "http://postcrm.herokuapp.com/window/collection", :class => "btn btn-primary btn-lg btn-block", :method => :post %>
    <br>
    <%= button_to "Area Sold", "http://postcrm.herokuapp.com/window/area_sold", :class => "btn btn-primary btn-lg btn-block", :method => :post %>
    <br>
    <%= button_to "Milestones", "http://postcrm.herokuapp.com/window/milestones", :class => "btn btn-primary btn-lg btn-block", :method => :post %>
    <br>
    <%= button_to "Cash Flow", "http://postcrm.herokuapp.com/window/cash_outflow", :class => "btn btn-primary btn-lg btn-block", :method => :post %>

  </div>
  </div>
</div>

</div>

app/views/reports/index.html.erb
<div class="card border-primary mb-3" style="max-width: 30rem;">
<center>  
  <div class="card-header"></div>
  <div class="card-body">
    <h2 class="card-title">Transaction</h2>
      <ul class="list-group">

        <li class="list-group-item">
        <span class="badge"><%= %></span>
          <a>
          <span></span> 
          <%= link_to 'Money Receipt Register', {controller: 'reports', action: 'money_receipt_register'}, {method: :post} %>
          </a>
        </li>        

      </ul>
  </div>
</center>
</div>

app/views/reports/money_receipt_register.html.erb
<%= form_tag 'money_receipt_register', :authenticity_token => true, :html => {:class => 'form-horizontal'}  do %>
<div class="row row_position">
  <div class="col-sm-12">
    <div class='col-sm-3' id='total_amt'></div>
    <div class="col-sm-6">
      <b>Money Receipts During</b>
      <div class="col-sm-9">
        <%= date_field(:range, :from, :value => @from,:style=>"line-height:19px;") %>
        To:<%= date_field(:range, :to, :value => @to,:style=>"line-height:19px;") %>
        <%= submit_tag "Refresh", name: "refresh", :class => 'btn btn-primary btn-xs' %>
      </div>
    </div>
  </div>      
</div>

<table class="table table-striped table-hover" id='money_receipt_register'>
  <thead>
   <tr>
      <th></th>
      <th>Date</th>
      <th>Customer</th>
      <th>Instrument</th>
      <th>Link</th>
      <th>RP Number</th>
      <th>Lottery Details</th>
      <th>Lottery(₹)</th>
      <th>Recd(₹)</th>
      <th></th>
   </tr>
  </thead>

  <tbody>
    <% @money_receipts.each do |money_receipt| %>
    <tr>
      <td><%= check_box_tag 'printables[]', money_receipt.id%></td>
      <td><%= money_receipt.created_at.strftime("%d/%m/%y") %></td>
      <td><%= money_receipt.customer.name %></td>
      <td><%= money_receipt.instrument_detail %></td>
      <% if money_receipt.instrument==nil %>
      <td></td>
      <% else %>
      <td><%= link_to money_receipt.instrument.scan_file_name, money_receipt.instrument.scan.url, target: :_blank %></td>
      <% end %>
      <td><%= money_receipt.rp_number %></td>
      <td>
      <% amount=0 %>  
      <% money_receipt.sold_lotteries.each do |sold_lottery| %>
        <b><%= sold_lottery.lottery.name %>(<%= sold_lottery.lottery.rate.round %>)</b>:
        <% sold_lottery.sold_series.each do |sold_series| %>
          <i><%= sold_series.series.name %></i>-
          <% sold_series.sold_numbers.each do |sold_number| %>
            <small><%= sold_number.serial %></small>
            <% if sold_number.sold_series.series.name=='all' || sold_number.sold_series.series.name=='All' %>
            <% amount+=((sold_number.sold_series.sold_lottery.lottery.rate)*((sold_number.sold_series.sold_lottery.lottery.series.count-1))) %>
            <% else %>
            <% amount+=sold_number.sold_series.sold_lottery.lottery.rate %>
            <% end %>
          <% end %> 
        <% end %>
      <% end %>  
      </td>
      <td><%= amount.round %></td>
      <td><%= money_receipt.amount.round %></td>
      <td><%= link_to 'Review', transaction_money_receipt_review_url(:money_receipt_id => money_receipt.id), method: "get", :target => "_blank" %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<div class="col-sm-6">
<%= submit_tag "Print", name: "print", :class => 'btn btn-primary' %>
</div>
<% end %>